# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1239, 879)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter_6 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setChildrenCollapsible(False)
        self.splitter_6.setObjectName("splitter_6")
        self.groupBox_5 = QtWidgets.QGroupBox(self.splitter_6)
        self.groupBox_5.setMinimumSize(QtCore.QSize(264, 691))
        self.groupBox_5.setBaseSize(QtCore.QSize(100, 0))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter_2 = QtWidgets.QSplitter(self.groupBox_5)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setChildrenCollapsible(False)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.frame = QtWidgets.QLabel(self.splitter)
        self.frame.setObjectName("frame")
        self.lineEdit = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit.setObjectName("lineEdit")
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_2)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setChildrenCollapsible(False)
        self.splitter_3.setObjectName("splitter_3")
        self.numlabel = QtWidgets.QLabel(self.splitter_3)
        self.numlabel.setObjectName("numlabel")
        self.num = QtWidgets.QLineEdit(self.splitter_3)
        self.num.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num.sizePolicy().hasHeightForWidth())
        self.num.setSizePolicy(sizePolicy)
        self.num.setSizeIncrement(QtCore.QSize(12, 0))
        self.num.setObjectName("num")
        self.splitter_5 = QtWidgets.QSplitter(self.splitter_2)
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setChildrenCollapsible(False)
        self.splitter_5.setObjectName("splitter_5")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_5)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rangelabel = QtWidgets.QLabel(self.layoutWidget)
        self.rangelabel.setObjectName("rangelabel")
        self.horizontalLayout_2.addWidget(self.rangelabel)
        self.velocitylabel = QtWidgets.QLabel(self.layoutWidget)
        self.velocitylabel.setObjectName("velocitylabel")
        self.horizontalLayout_2.addWidget(self.velocitylabel)
        self.splitter_4 = QtWidgets.QSplitter(self.splitter_5)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setChildrenCollapsible(False)
        self.splitter_4.setObjectName("splitter_4")
        self.range = QtWidgets.QTextEdit(self.splitter_4)
        self.range.setObjectName("range")
        self.velocity = QtWidgets.QTextEdit(self.splitter_4)
        self.velocity.setEnabled(True)
        self.velocity.setObjectName("velocity")
        self.plotpushButton = QtWidgets.QPushButton(self.splitter_2)
        self.plotpushButton.setObjectName("plotpushButton")
        self.gridLayout.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.splitter_6)
        self.groupBox_4.setMinimumSize(QtCore.QSize(801, 811))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.xyplot = matplotlibwidget(self.groupBox_4)
        self.xyplot.setObjectName("xyplot")
        self.gridLayout_4.addWidget(self.xyplot, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.splitter_6, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1239, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_5.setTitle(_translate("MainWindow", "目标信息"))
        self.frame.setText(_translate("MainWindow", "当前帧数："))
        self.numlabel.setText(_translate("MainWindow", "目标个数："))
        self.rangelabel.setText(_translate("MainWindow", "目标距离："))
        self.velocitylabel.setText(_translate("MainWindow", "目标速度："))
        self.plotpushButton.setText(_translate("MainWindow", "开始绘图"))
        self.groupBox_4.setTitle(_translate("MainWindow", "坐标"))

from MatplotlibWidget import matplotlibwidget
