# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 500)
        MainWindow.setBaseSize(QtCore.QSize(2000, 1800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.splitter_5 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setChildrenCollapsible(False)
        self.splitter_5.setObjectName("splitter_5")
        self.information_groupBox = QtWidgets.QGroupBox(self.splitter_5)
        self.information_groupBox.setMinimumSize(QtCore.QSize(350, 0))
        self.information_groupBox.setMaximumSize(QtCore.QSize(400, 16777215))
        self.information_groupBox.setBaseSize(QtCore.QSize(100, 0))
        self.information_groupBox.setObjectName("information_groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.information_groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.information_groupBox)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.freq_label = QtWidgets.QLabel(self.layoutWidget)
        self.freq_label.setObjectName("freq_label")
        self.horizontalLayout.addWidget(self.freq_label)
        self.freq_line = QtWidgets.QLineEdit(self.layoutWidget)
        self.freq_line.setReadOnly(True)
        self.freq_line.setObjectName("freq_line")
        self.horizontalLayout.addWidget(self.freq_line)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 4)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.width_label = QtWidgets.QLabel(self.layoutWidget1)
        self.width_label.setObjectName("width_label")
        self.horizontalLayout_2.addWidget(self.width_label)
        self.width_line = QtWidgets.QLineEdit(self.layoutWidget1)
        self.width_line.setReadOnly(True)
        self.width_line.setObjectName("width_line")
        self.horizontalLayout_2.addWidget(self.width_line)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 4)
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.r_max_label = QtWidgets.QLabel(self.layoutWidget2)
        self.r_max_label.setObjectName("r_max_label")
        self.horizontalLayout_3.addWidget(self.r_max_label)
        self.r_max_line = QtWidgets.QLineEdit(self.layoutWidget2)
        self.r_max_line.setReadOnly(True)
        self.r_max_line.setObjectName("r_max_line")
        self.horizontalLayout_3.addWidget(self.r_max_line)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 4)
        self.layoutWidget3 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.r_res_label = QtWidgets.QLabel(self.layoutWidget3)
        self.r_res_label.setObjectName("r_res_label")
        self.horizontalLayout_4.addWidget(self.r_res_label)
        self.r_res_line = QtWidgets.QLineEdit(self.layoutWidget3)
        self.r_res_line.setReadOnly(True)
        self.r_res_line.setObjectName("r_res_line")
        self.horizontalLayout_4.addWidget(self.r_res_line)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(1, 4)
        self.layoutWidget4 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.v_max_label = QtWidgets.QLabel(self.layoutWidget4)
        self.v_max_label.setObjectName("v_max_label")
        self.horizontalLayout_5.addWidget(self.v_max_label)
        self.v_max_line = QtWidgets.QLineEdit(self.layoutWidget4)
        self.v_max_line.setReadOnly(True)
        self.v_max_line.setObjectName("v_max_line")
        self.horizontalLayout_5.addWidget(self.v_max_line)
        self.horizontalLayout_5.setStretch(0, 2)
        self.horizontalLayout_5.setStretch(1, 4)
        self.layoutWidget5 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.v_res_label = QtWidgets.QLabel(self.layoutWidget5)
        self.v_res_label.setObjectName("v_res_label")
        self.horizontalLayout_6.addWidget(self.v_res_label)
        self.v_res_line = QtWidgets.QLineEdit(self.layoutWidget5)
        self.v_res_line.setReadOnly(True)
        self.v_res_line.setObjectName("v_res_line")
        self.horizontalLayout_6.addWidget(self.v_res_line)
        self.horizontalLayout_6.setStretch(0, 2)
        self.horizontalLayout_6.setStretch(1, 4)
        self.layoutWidget6 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.camerapushButton = QtWidgets.QPushButton(self.layoutWidget6)
        self.camerapushButton.setObjectName("camerapushButton")
        self.horizontalLayout_7.addWidget(self.camerapushButton)
        self.plotpushButton = QtWidgets.QPushButton(self.layoutWidget6)
        self.plotpushButton.setObjectName("plotpushButton")
        self.horizontalLayout_7.addWidget(self.plotpushButton)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.splitter_4 = QtWidgets.QSplitter(self.splitter_5)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setChildrenCollapsible(False)
        self.splitter_4.setObjectName("splitter_4")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_4)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setChildrenCollapsible(False)
        self.splitter_2.setObjectName("splitter_2")
        self.rd_groupBox = QtWidgets.QGroupBox(self.splitter_2)
        self.rd_groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.rd_groupBox.setAutoFillBackground(True)
        self.rd_groupBox.setFlat(False)
        self.rd_groupBox.setCheckable(False)
        self.rd_groupBox.setObjectName("rd_groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.rd_groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rdplot = matplotlibwidget(self.rd_groupBox)
        self.rdplot.setObjectName("rdplot")
        self.gridLayout_2.addWidget(self.rdplot, 0, 0, 1, 1)
        self.camera_groupBox = QtWidgets.QGroupBox(self.splitter_2)
        self.camera_groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.camera_groupBox.setAutoFillBackground(False)
        self.camera_groupBox.setObjectName("camera_groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.camera_groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.camera = QtWidgets.QLabel(self.camera_groupBox)
        self.camera.setMinimumSize(QtCore.QSize(800, 500))
        self.camera.setAutoFillBackground(False)
        self.camera.setText("")
        self.camera.setObjectName("camera")
        self.gridLayout_3.addWidget(self.camera, 0, 0, 1, 1)
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_4)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setChildrenCollapsible(False)
        self.splitter_3.setObjectName("splitter_3")
        self.radar_groupBox = QtWidgets.QGroupBox(self.splitter_3)
        self.radar_groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.radar_groupBox.setAutoFillBackground(True)
        self.radar_groupBox.setObjectName("radar_groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.radar_groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.radarplot = polarwidget(self.radar_groupBox)
        self.radarplot.setObjectName("radarplot")
        self.gridLayout_5.addWidget(self.radarplot, 0, 0, 1, 1)
        self.location_groupBox_4 = QtWidgets.QGroupBox(self.splitter_3)
        self.location_groupBox_4.setMinimumSize(QtCore.QSize(0, 0))
        self.location_groupBox_4.setAutoFillBackground(True)
        self.location_groupBox_4.setObjectName("location_groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.location_groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.xyplot = matplotlibwidget(self.location_groupBox_4)
        self.xyplot.setObjectName("xyplot")
        self.gridLayout_4.addWidget(self.xyplot, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.splitter_5, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2000, 19))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "道路雷达监测系统"))
        self.information_groupBox.setTitle(_translate("MainWindow", "雷达信息"))
        self.freq_label.setText(_translate("MainWindow", "工作频率："))
        self.width_label.setText(_translate("MainWindow", "工作带宽："))
        self.r_max_label.setText(_translate("MainWindow", "最大测距："))
        self.r_res_label.setText(_translate("MainWindow", "距离分辨率："))
        self.v_max_label.setText(_translate("MainWindow", "最大测速："))
        self.v_res_label.setText(_translate("MainWindow", "速度分辨率："))
        self.camerapushButton.setText(_translate("MainWindow", "打开相机"))
        self.plotpushButton.setText(_translate("MainWindow", "开始绘图"))
        self.rd_groupBox.setTitle(_translate("MainWindow", "距离多普勒图"))
        self.camera_groupBox.setTitle(_translate("MainWindow", "视频图"))
        self.radar_groupBox.setTitle(_translate("MainWindow", "PPI图"))
        self.location_groupBox_4.setTitle(_translate("MainWindow", "前视图"))


from MatplotlibWidget import matplotlibwidget
from PolarWidget import polarwidget
